import { Extension } from "@/types/extension";

// Static catalog — no network fetch, no download. Ships inside the app bundle.
export const catalog: Extension[] = [
  {
    id: "prettier",
    name: "Prettier - Code formatter",
    publisher: "Prettier",
    verified: true,
    description: "Code formatter using prettier",
    icon: "🎨",
    iconBg: "#1A2B34",
    version: "1.0.0",
    rating: 4.5,
    reviewCount: 1240,
    downloads: "45M",
    category: "Formatters",
  },
  {
    id: "eslint",
    name: "ESLint",
    publisher: "Microsoft",
    verified: true,
    description: "Integrates ESLint into the editor for linting JS/TS",
    icon: "🔍",
    iconBg: "#4B32C3",
    version: "1.0.0",
    rating: 4.3,
    reviewCount: 980,
    downloads: "32M",
    category: "Linters",
  },
  {
    id: "one-dark-theme",
    name: "One Dark Pro",
    publisher: "binaryify",
    verified: true,
    description: "Atom's iconic One Dark theme for your editor",
    icon: "🌑",
    iconBg: "#282C34",
    version: "1.0.0",
    rating: 4.9,
    reviewCount: 3400,
    downloads: "9M",
    category: "Themes",
  },
  {
    id: "material-icons",
    name: "Material Icon Theme",
    publisher: "PKief",
    verified: true,
    description: "Material Design icons for your files and folders",
    icon: "📁",
    iconBg: "#0B57D0",
    version: "1.0.0",
    rating: 4.8,
    reviewCount: 2100,
    downloads: "40M",
    category: "Themes",
  },
  {
    id: "auto-close-tags",
    name: "Auto Close Tag",
    publisher: "formulahendry",
    verified: false,
    description: "Automatically add HTML/XML close tags",
    icon: "🏷️",
    iconBg: "#B23A48",
    version: "1.0.0",
    rating: 4.4,
    reviewCount: 560,
    downloads: "12M",
    category: "Other",
  },
];

export const categories = [
  "All categories",
  "Themes",
  "Formatters",
  "Linters",
  "Other",
];
