# syntax=docker/dockerfile:1
#
# mcode monorepo — multi-stage image for the backend API and the web frontend.
#
# Why this is a multi-stage build (the old single-stage one could never work):
#
#   1. node-pty / cpu-features / ssh2 are NATIVE modules. The Windows host's
#      node_modules cannot be reused in a Linux container — the win32 .node
#      binaries fail to load and the backend dies on boot. So `npm ci` runs
#      INSIDE the image, against Alpine's musl, with a real toolchain.
#   2. The toolchain (python3/make/g++) is needed to COMPILE, never to RUN.
#      Keeping it in the final stage bloated the runtime image for nothing.
#   3. The web app needs `next build` output plus devDependencies. The
#      backend does not. One image serving both meant shipping both sets.
#
# Result: build stage has the toolchain and runs next build; the runtime
# stage is a clean production image with no compilers.

# ─── Base ─────────────────────────────────────────────────────────────────────
# Node 24 matches the local dev runtime (node v24.16.0).
#
# The npm major version matters as much as the node version here: package-lock
# is generated by npm 12, and `npm ci` in an image that ships npm 10 rejects it
# with "Missing: search-insights@x from lock file" — npm 10 resolves the
# optional @docsearch/react peer differently than npm 12 recorded. Pinning npm
# keeps `npm ci` (lockfile-exact, reproducible) working instead of degrading to
# `npm install`.
FROM node:24-alpine AS base
WORKDIR /app
RUN npm install -g npm@12
ENV npm_config_fund=false \
    npm_config_audit=false \
    NEXT_TELEMETRY_DISABLED=1 \
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
# BusyBox wget backs the HEALTHCHECK below — no curl needed in the image.
RUN apk add --no-cache wget

# ─── deps: install the monorepo dependency tree ───────────────────────────────
FROM base AS deps
# Native modules compile from source on musl, so we need a toolchain HERE.
RUN apk add --no-cache python3 make g++

# Copy ONLY manifests first. This layer is cached until a package.json or the
# lockfile changes, so day-to-day source edits skip the whole install.
COPY package.json package-lock.json ./
COPY packages/backend/package.json packages/backend/
COPY packages/cli/package.json     packages/cli/
COPY packages/shared/package.json   packages/shared/
COPY packages/web/package.json     packages/web/
# `scripts/` must exist BEFORE npm ci: the root package.json declares a
# `postinstall` (scripts/bootstrap.js), and a failing lifecycle script makes
# the whole `npm ci` — and therefore the build — fail.
COPY scripts/bootstrap.js    scripts/bootstrap.js
COPY scripts/install-hooks.mjs scripts/install-hooks.mjs

# `npm ci` (not `npm install`) for a reproducible, lockfile-exact tree.
# --ignore-scripts is deliberately NOT used: it would skip the node-gyp
# compiles for node-pty/ssh2 and produce an image that cannot boot.
# PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD is set in `base` — playwright is a
# dependency of both backend and cli, and downloading ~500MB of browsers
# would triple the build time for nothing the server needs.
RUN npm ci --no-fund --no-audit

# ─── build: compile the CLI bundle and the Next.js production build ───────────
FROM base AS build
RUN apk add --no-cache python3 make g++
COPY --from=deps /app/node_modules ./node_modules
COPY package.json package-lock.json ./
COPY packages/backend ./packages/backend
COPY packages/cli     ./packages/cli
COPY packages/shared   ./packages/shared
COPY packages/web     ./packages/web
COPY scripts           ./scripts

# NEXT_PUBLIC_* values are inlined at build time, so the browser-side API
# origin has to be baked in here. Default to the published host port; the
# compose file overrides this with the service name for server-side calls.
ARG NEXT_PUBLIC_API_URL=http://localhost:3100
ARG BACKEND_URL=http://backend:3100
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    BACKEND_URL=$BACKEND_URL \
    NEXT_TELEMETRY_DISABLED=1

# esbuild bundles the CLI to a single dist/mcode.mjs.
RUN npm run build:cli
# next build produces .next/ — the artifact the web runtime stage serves.
RUN npm run build:web

# ─── backend: production runtime for the Express + Socket.IO API ──────────────
FROM base AS backend
ENV NODE_ENV=production \
    PORT=3100
# tini reaps orphaned child processes (node-pty spawns shells), so a crashed
# PTY session cannot leave zombies accumulating in the container.
# git  -> simple-git operations against user repos
# busybox-extras -> `nc`, used by the entrypoint to probe mongo/redis
RUN apk add --no-cache tini git busybox-extras

# Re-install production-only deps instead of copying the build stage's
# dev-heavy tree, so nodemon/vitest/next never ship to production.
COPY package.json package-lock.json ./
COPY packages/backend/package.json packages/backend/
COPY packages/cli/package.json     packages/cli/
COPY packages/shared/package.json   packages/shared/
COPY packages/web/package.json     packages/web/
# Root postinstall target — see the deps stage for why this ordering matters.
COPY scripts/bootstrap.js    scripts/bootstrap.js
COPY scripts/install-hooks.mjs scripts/install-hooks.mjs
# `--include-workspace-root` pulls in the root manifest's own deps, which the
# backend resolves at runtime. Omitting it produced a container that booted
# and then threw MODULE_NOT_FOUND on the first import.
RUN npm ci --omit=dev --no-fund --no-audit \
      --workspace=@mcode/backend --include-workspace-root

COPY packages/backend ./packages/backend
COPY packages/cli     ./packages/cli
COPY packages/shared   ./packages/shared
COPY --from=build /app/packages/cli/dist ./packages/cli/dist
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 3100
# /health reports storage/cache/queue + execution capabilities. Alpine's
# BusyBox wget is already present from `base`.
HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3100/health >/dev/null 2>&1 || exit 1

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]
# main.js (not server.js) — server.js only exports startServer(); main.js is
# what actually calls it. The old CMD pointed at server.js and exited silently.
CMD ["node", "packages/backend/src/main.js"]

# ─── web: production runtime for the Next.js frontend ─────────────────────────
FROM base AS web
ENV NODE_ENV=production \
    PORT=3000
RUN apk add --no-cache tini
COPY --from=build /app/node_modules            ./node_modules
COPY --from=build /app/packages/web/node_modules ./packages/web/node_modules
COPY --from=build /app/packages/web/.next      ./packages/web/.next
COPY --from=build /app/packages/web/public     ./packages/web/public
COPY --from=build /app/packages/web/package.json ./packages/web/package.json
COPY --from=build /app/packages/web/next.config.mjs ./packages/web/next.config.mjs

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3000/ >/dev/null 2>&1 || exit 1

WORKDIR /app/packages/web
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npx", "next", "start", "-p", "3000"]
