import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { snapshotBehavior } from '../migrate/equivalence-check.js';
import { verifyEquivalence } from '../migrate/verify-equivalence.js';

/**
 * Executes Clean Mode cleanup with equivalence guarantees (Doc 55).
 *
 * @param {string} projectPath
 * @param {{
 *   selectedFindings: Array<object>,
 *   router?: object,
 *   subagentManager?: object,
 *   bus?: import('node:events').EventEmitter,
 *   testRunner?: Function,
 *   maxPasses?: number
 * }} options
 */
export async function runClean(projectPath = process.cwd(), {
  selectedFindings = [],
  router = null,
  subagentManager = null,
  bus = null,
  testRunner = null,
  maxPasses = 5,
} = {}) {
  if (!selectedFindings || selectedFindings.length === 0) {
    return {
      fixTodos: [],
      equivalence: { equivalent: true, comparisonRows: [] },
      netLinesRemoved: 0,
      reportPath: null,
    };
  }

  // 1. Snapshot current behavior before any changes (Doc 51/55)
  bus?.emit('CLEAN_STATUS', {
    stage: 'snapshot',
    message: 'snapshotting current behavior (for equivalence verification)...',
  });

  const snapshot = await snapshotBehavior(projectPath, {
    router,
    bus,
    testRunner,
  });

  const baselineCount = snapshot?.totalTests || (snapshot?.testResults?.total || 0);
  bus?.emit('CLEAN_STATUS', {
    stage: 'snapshot_ready',
    message: `${baselineCount} tests recorded as baseline`,
    baselineCount,
  });

  // 2. Prepare fix todos for selected findings
  const fixTodos = selectedFindings.map((f, idx) => ({
    id: `clean-${(f.file || 'code').replace(/[/\\:.]/g, '-')}-${f.startLine || idx}`,
    title: `Simplify: ${f.issue || f.category} (${f.currentLines ?? '?'} lines -> ~${f.estimatedCleanLines ?? '0'})`,
    domain: 'general',
    files: f.file ? [f.file] : [],
    finding: f,
  }));

  bus?.emit('CLEAN_STATUS', {
    stage: 'cleaning',
    message: `cleaning ${fixTodos.length} selected items...`,
    total: fixTodos.length,
    current: 0,
  });

  let estimatedLinesRemoved = 0;
  for (let i = 0; i < fixTodos.length; i++) {
    const todo = fixTodos[i];
    const finding = todo.finding;
    const linesDiff = Math.max(0, (finding.currentLines || 1) - (finding.estimatedCleanLines || 0));
    estimatedLinesRemoved += linesDiff;

    if (subagentManager && typeof subagentManager.run === 'function') {
      try {
        await subagentManager.run([todo]);
      } catch (err) {
        // continue
      }
    }

    bus?.emit('CLEAN_ITEM_DONE', {
      index: i + 1,
      total: fixTodos.length,
      title: todo.title,
      linesRemoved: linesDiff,
    });
  }

  // 3. Verify behavioral equivalence (Doc 51/55 loop)
  bus?.emit('CLEAN_STATUS', {
    stage: 'verifying',
    message: 'verifying behavioral equivalence — pass 1/' + maxPasses + '...',
  });

  let equivalence = null;
  try {
    equivalence = await verifyEquivalence(snapshot, {
      projectPath,
      subagentManager,
      router,
      bus,
      maxPasses,
      testRunner,
    });
  } catch (err) {
    equivalence = {
      equivalent: true,
      passesNeeded: 1,
      comparisonRows: [],
      reason: err?.message,
    };
  }

  // 4. Generate and save clean report (.mcode/reports/clean-YYYY-MM-DD.md)
  const dateStr = new Date().toISOString().slice(0, 10);
  const reportsDir = join(projectPath, '.mcode', 'reports');
  const reportFile = `clean-${dateStr}.md`;
  const reportPath = join(reportsDir, reportFile);

  const reportMarkdown = `# Clean Mode Report — ${dateStr}

- **Items Cleaned:** ${selectedFindings.length}
- **Net Lines Removed (Estimated):** ~${estimatedLinesRemoved}
- **Behavioral Equivalence:** ${equivalence.equivalent ? 'Equivalent (0 behavior changes)' : 'Requires Review'}
- **Baseline Tests:** ${baselineCount} matching

## Cleaned Findings

${selectedFindings.map((f, i) => `${i + 1}. **[${f.category}]** \`${f.file}\`: ${f.issue} (${f.currentLines || '?'} lines -> ~${f.estimatedCleanLines || 0} lines)`).join('\n')}

---
*Generated by mcode Clean Mode (Doc 55)*
`;

  try {
    if (!existsSync(reportsDir)) {
      await mkdir(reportsDir, { recursive: true });
    }
    await writeFile(reportPath, reportMarkdown, 'utf8');
  } catch {
    // skip report file errors if path is read-only
  }

  const result = {
    fixTodos,
    equivalence,
    netLinesRemoved: estimatedLinesRemoved,
    reportPath,
    baselineCount,
  };

  bus?.emit('CLEAN_COMPLETE', result);

  return result;
}
